version: '3.4'

services:

  unicornstore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # The below environment variables are an example.
      # Never store passwords or other sensitive data in configuration provider code or in plain text configuration files.
      # Don't use production secrets in development or test environments.
      # Specify secrets outside of the project so that they can't be accidentally committed to a source code repository.
      # You need to UNCOMMENT the below and insert your db specific information. 
      #- UNICORNSTORE_DBSECRET={"username":"unicorndbuser","password":"unicorndbpassword","engine":"sqlserver","host":"unicorn-db-us-west-2.rds.amazonaws.com","port":1433,"dbInstanceIdentifier":"unicorn-db"}
      #- DefaultAdminUsername=Administrator@test.com
      #- DefaultAdminPassword=Secret1*
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
